//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevelopmentChallenge.Data.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DevelopmentChallenge.Data.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area.
        /// </summary>
        internal static string area {
            get {
                return ResourceManager.GetString("area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Círculo.
        /// </summary>
        internal static string circulo {
            get {
                return ResourceManager.GetString("circulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuadrado.
        /// </summary>
        internal static string cuadrado {
            get {
                return ResourceManager.GetString("cuadrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forma.
        /// </summary>
        internal static string forma {
            get {
                return ResourceManager.GetString("forma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reporte de Formas.
        /// </summary>
        internal static string listanovacia {
            get {
                return ResourceManager.GetString("listanovacia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista vacía de formas!.
        /// </summary>
        internal static string listavacia {
            get {
                return ResourceManager.GetString("listavacia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perímetro.
        /// </summary>
        internal static string perimetro {
            get {
                return ResourceManager.GetString("perimetro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rectángulo.
        /// </summary>
        internal static string rectangulo {
            get {
                return ResourceManager.GetString("rectangulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trapecio.
        /// </summary>
        internal static string trapecio {
            get {
                return ResourceManager.GetString("trapecio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Triángulo Equilátero.
        /// </summary>
        internal static string trianguloequilatero {
            get {
                return ResourceManager.GetString("trianguloequilatero", resourceCulture);
            }
        }
    }
}
